Khant's student bio
HYF-Class22/home pull request #58
Opened 2024-01-28 14:10 UTC by khantm02

- [ ] clone the home repo
- [ ] create a new branch "khant"
- [ ] run npm install 
- [ ] create a new file "khantm02.md" 
- [ ] add my image to img folder
- [ ]  add info about me to "khantm02.md" 
- [ ] npm run format, npm run format:check
- [ ] npm run spell-check
- [ ] npm run lint:ls, npm run lint:md
- [ ] add my changes to the staging area
- [ ] commit my changes
- [ ] push my code to GitHub
- [ ] make pull request

2024-01-28 20:10 UTC, denisrossi commented on student-bios/khantm02.md
I guess you want to add some markdown content :stuck_out_tongue_closed_eyes: 

You can find [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) the basic syntax for the Github flavor of markdown

2024-01-29 21:25 UTC, samirm00 commented
Hello @khantm02 please create a deliverable issue and link it to your `PR`

2024-02-02 00:44 UTC, khantm02 commented on student-bios/khantm02.md
Hi coach, I have written the README file. The problem is I cloned the repo again, created a new branch, committed the changes and tried to push it again. I cannot push it because it is showing me an error. I tried doing that way as I could not figure out how to access my branch for this pull request again. I hope you understood my point.

2024-02-02 11:35 UTC, bermarte commented
The file is empty, write some markdown.

2024-02-02 15:41 UTC, bermarte requested changes
All the images should go to the img folder (no logos, delete it), you can't use HTML in Markdown. Your profile image is too dark.

2024-02-02 17:37 UTC, khantm02 commented
Hi coach, I have fixed these issues. I just listed the technology stack instead of photos. I deleted the logo album as well. The reason I used html tag was to resize my profile image. I hope everything is good now.

2024-02-07 00:36 UTC, closed without merging