add hitomipupil
HYF-Class22/home pull request #72
Opened 2024-02-01 16:01 UTC by hitomipupil

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

2024-02-02 01:53 UTC, bermarte commented
You shouldn't use the same text for 2 different commits, always explain in simple terms what that commit will do, if the commit will fix a previous problem (file empty), you will mention it.

2024-02-02 01:55 UTC, bermarte requested changes

2024-02-02 01:55 UTC, bermarte commented on student-bios/hitomipupil.md
> +![hitomi](https://ca.slack-edge.com/T04N0HHDQCW-U065R2TRSG1-afb7ac8b1e26-512)
Copy the file in a img folder inside student-bio, it's better to have no inline code of this kind.

2024-02-02 01:58 UTC, hitomipupil commented
> You shouldn't use the same text for 2 different commits, always explain in simple terms what that commit will do, if the commit will fix a previous problem (file empty), you will mention it.

@bermarte I see. I will be careful from next time.

2024-02-02 01:58 UTC, hitomipupil commented on student-bios/hitomipupil.md
> +![hitomi](https://ca.slack-edge.com/T04N0HHDQCW-U065R2TRSG1-afb7ac8b1e26-512)
> Copy the file in a img folder inside student-bio, it's better to have no inline code of this kind.

I see, I will try it. Thank you for checking it.

2024-02-07 00:39 UTC, samirm00 approved these changes

2024-02-07 00:40 UTC, closed without merging